name: Add new study
description: Submit a new study entry in YAML format
labels: [reviewed]
body:
  - type: markdown
    attributes:
      value: |
        Paste your study metadata below inside:

        ```yaml
        <your YAML here>
        ```
  - type: textarea
    id: entry
    attributes:
      label: Study YAML
      description: Paste YAML describing this study.
      placeholder: |
        ```yaml
        doi: ...
        taxid: ...
        individuals: ...
        data_url: ...
        method: ...
        notes: |
          ...
        ```
    validations:
      required: true
