name: "📚 New Study Submission"
description: Submit a new wildlife epigenetics study for review
title: "[STUDY] Add new study"
labels: ["new-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all fields below. After review, we'll add it to the catalog.

  - type: input
    id: doi
    attributes:
      label: DOI
      description: e.g. `10.1038/s41586-024-12345-6`
      placeholder: "10.1038/..."
    validations:
      required: true

  - type: input
    id: taxid
    attributes:
      label: NCBI Taxon ID
      description: e.g. `9606` for human, `10090` for mouse
      placeholder: "9606"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Notes (optional)
      placeholder: "..."

  - type: markdown
    attributes:
      value: |
        **After submission, a maintainer will review and apply the `reviewed` label to process it.**
