name: "📚 New Study Submission"
description: Submit a new wildlife epigenetics study for review
title: "[STUDY] Add new study"
labels: ["new-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all fields below. After review, we'll add it to the catalog.

  - type: input
    id: doi
    attributes:
      label: article DOI
      description: e.g. `10.1038/s41586-024-12345-6`
      placeholder: "10.1038/..."
    validations:
      required: true

  - type: input
    id: taxid
    attributes:
      label: NCBI Taxon ID
      description: e.g. `9606` for human, `10090` for mouse; find yours at https://www.ncbi.nlm.nih.gov/datasets/taxonomy/tree/
      placeholder: "9606"
    validations:
      required: true

  - type: input
    id: tissue
    attributes:
      label: tissue sampled
      description: e.g. blood, liver...
      placeholder: "blood"
    validations:
      required: true

  - type: input
    id: data_url
    attributes:
      label: URL of raw data
      description: link to the list of raw data
      placeholder: "https://www.ncbi.nlm.nih.gov/sra/?term=SRP058411"
    validations:
      required: true

  - type: input
    id: method
    attributes:
      label: method
      description: e.g. `RRBS, WGBS...`
      placeholder: "RRBS"
    validations:
      required: true
      
  - type: input
    id: individuals
    attributes:
      label: number of sequenced individuals
      description: e.g. `10, 15...`
      placeholder: "10"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: topic(s) of the study
      placeholder: "..."
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        **After submission, a maintainer will review and apply the `reviewed` label to process it.**
